services:
  # PostgreSQL database service
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: new_york_taxi
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
  # PGAdmin service for UI access to Postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80" 

volumes:
  pgdata: