services:
  # python_docker_environment:
  #   build: .
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - database
  #   command: >
  #     python data_extraction.py
  #     https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz
  #     root root database 5432 new_york_taxi yellow_tripdata
  #   stdin_open: true
  #   tty: true

  database:
    image: postgres:13
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: new_york_taxi
    volumes:
      - ./postgres_data:/var/lib/postgres/data:rw
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"